
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parsers;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int eq = 54;
  public static final int orArith = 52;
  public static final int mod = 50;
  public static final int intTer = 11;
  public static final int andLog = 60;
  public static final int string_const = 66;
  public static final int orLog = 61;
  public static final int elseTer = 31;
  public static final int openCurly = 9;
  public static final int minus = 47;
  public static final int repeat = 36;
  public static final int div = 49;
  public static final int addAssign = 70;
  public static final int dot = 72;
  public static final int lte = 57;
  public static final int ifTer = 30;
  public static final int switchTer = 32;
  public static final int colon = 34;
  public static final int semiColon = 5;
  public static final int andArith = 51;
  public static final int constTer = 23;
  public static final int begin = 21;
  public static final int notLog = 43;
  public static final int longTer = 14;
  public static final int forTer = 35;
  public static final int openBrace = 7;
  public static final int openParen = 3;
  public static final int char_const = 64;
  public static final int string = 17;
  public static final int in = 39;
  public static final int function = 73;
  public static final int gte = 56;
  public static final int voidTer = 18;
  public static final int id = 2;
  public static final int ic = 42;
  public static final int of = 33;
  public static final int end = 22;
  public static final int auto = 19;
  public static final int long_const = 67;
  public static final int prodAssign = 69;
  public static final int bool = 12;
  public static final int MinusMinus = 44;
  public static final int neq = 55;
  public static final int until = 37;
  public static final int charTer = 15;
  public static final int xor = 53;
  public static final int comma = 25;
  public static final int sizeof = 29;
  public static final int foreach = 38;
  public static final int EOF = 0;
  public static final int closeCurly = 10;
  public static final int gt = 59;
  public static final int PlusPlus = 45;
  public static final int bool_const = 65;
  public static final int divAssign = 68;
  public static final int error = 1;
  public static final int doubleTer = 16;
  public static final int caseTer = 41;
  public static final int defaultTer = 40;
  public static final int prod = 48;
  public static final int floatTer = 13;
  public static final int record = 20;
  public static final int assign = 24;
  public static final int closeBrace = 8;
  public static final int continueTer = 28;
  public static final int lt = 58;
  public static final int closeParen = 4;
  public static final int returnTer = 26;
  public static final int extern = 6;
  public static final int not = 62;
  public static final int subAssign = 71;
  public static final int real_const = 63;
  public static final int plus = 46;
  public static final int breakTer = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "openParen",
  "closeParen",
  "semiColon",
  "extern",
  "openBrace",
  "closeBrace",
  "openCurly",
  "closeCurly",
  "intTer",
  "bool",
  "floatTer",
  "longTer",
  "charTer",
  "doubleTer",
  "string",
  "voidTer",
  "auto",
  "record",
  "begin",
  "end",
  "constTer",
  "assign",
  "comma",
  "returnTer",
  "breakTer",
  "continueTer",
  "sizeof",
  "ifTer",
  "elseTer",
  "switchTer",
  "of",
  "colon",
  "forTer",
  "repeat",
  "until",
  "foreach",
  "in",
  "defaultTer",
  "caseTer",
  "ic",
  "notLog",
  "MinusMinus",
  "PlusPlus",
  "plus",
  "minus",
  "prod",
  "div",
  "mod",
  "andArith",
  "orArith",
  "xor",
  "eq",
  "neq",
  "gte",
  "lte",
  "lt",
  "gt",
  "andLog",
  "orLog",
  "not",
  "real_const",
  "char_const",
  "bool_const",
  "string_const",
  "long_const",
  "divAssign",
  "prodAssign",
  "addAssign",
  "subAssign",
  "dot",
  "function"
  };
}

